### ISSUE TITLE
Add support in the python script to read local sql files

### ISSUE THREAD

**Issue by rohitxsh** [rohitxsh/sql2parquet_py#3]
As the Covid genome data is available as a local SQL dump only, so add support to read such files and convert then into parquet files.

**Comment by bilalebi** [comment]
> Pandas does not support reading SQL dump files
> We can either load it in a local DB and read it from that local server
> Or we can read the file as a string and extract insert statements and process that, this is kinda a workaround and not recommended solution for production use but will work in most of the cases
> @andrewyatz @marcoooo @bilalebi Any suggestions on this

I think loading the data in local DB is the sensible approach, this will imitate production and be consistent with the configuration setup that we have in `config.toml`

**Comment by andrewyatz** [comment]
The easiest thing to do with this database is to load it into a local MySQL instance. I would suggest a docker image as the fastest way to get a MySQL v5.7 server up and running. Then have your script talk to that server. Certainly there's no reason why Pandas should be able to read SQL dump files at all

**Comment by rohitxsh** [comment]
Will be reading the data from local MySQL DB so this issue is no longer valid
Thanks for your inputs @bilalebi @andrewyatz
