### ISSUE TITLE
Update the python script to push parquet files directly to AWS S3 buckets

### ISSUE THREAD

**Issue by rohitxsh** [rohitxsh/sql2parquet_py#8]
Update the python script to push the generated parquet files directly to AWS S3 buckets

**Comment by rohitxsh** [comment]
Dependent on https://github.com/rohitxsh/sql2parquet_py/issues/5
Need to define the folder structure for respective tables and DBs for AWS S3 before pushing the files

**Comment by andrewyatz** [comment]
Okay I will raise a query with cloud consultants at EBI with you cc'd in

**Comment by cdtiwari-ebi** [comment]
Hey @andrewyatz and @rohitxsh permission has been updated, please check and confirm.

**Comment by rohitxsh** [comment]
Hi @cdtiwari-ebi @andrewyatz I can now create a new access key, thanks for the quick help.
